workflows:
  version: 2
  validate-config:
    jobs:
      - circle-lint
  multi-test:
    jobs:
      - test-node10
      - test-node12
  test_and_publish:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: npm
          requires:
            - test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
  static_analysis:
    jobs:
      - test
      - coverage:
          requires:
            - test
      - snyk:
          context: snyk
          requires:
            - test
  scheduled_e2e_test:
    triggers:
      - schedule:
          cron: "15 * * * *"
          filters:
            branches:
              only:
                - master
                - scheduled_e2e_testing
    jobs:
      - test-node10
      - test-node12

version: 2
jobs:
  circle-lint:
    working_directory: ~/analytics-node
    docker:
      - image: node
    steps:
      - checkout
      - run: yarn run circle-lint
  node-base-test: &node-base-test
    working_directory: ~/analytics-node
    docker:
      - image: node
    steps:
      - checkout
      - restore_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test
      - persist_to_workspace:
          root: .
          paths: [.]

  test-node10:
    <<: *node-base-test
    docker:
      - image: circleci/node:10-browsers
  test-node12:
    <<: *node-base-test
    docker:
      - image: circleci/node:12-browsers
  test:
    <<: *node-base-test
    docker:
      - image: circleci/node:10-browsers
  coverage:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: yarn run report-coverage
  snyk:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: yarn run snyk test --severity-threshold=high
      - run: yarn run snyk monitor
  publish:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish .
